### ISSUE TITLE
not working with newer version

### ISSUE THREAD

**Issue by Er-Abhishek-Kumar** [XPanel/Generic-EPP-with-DNSsec-Registrar-Module-for-WHMCS#2]
got error:

Error: Call to a member function read() on bool in /home/wixhost/public_html/modules/registrars/genericepp/genericepp.php:49
Stack trace:
#0 /home/wixhost/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): genericepp_getConfigArray(Array)
#1 /home/wixhost/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call('getConfigArray', Array)
#2 /home/wixhost/public_html/admin/configregistrars.php(0): WHMCS\Module\Registrar->call('getConfigArray')
#3 {main}

WHMCS Version: 7.8.3
PHP Version: 7.3

**Comment by joao-correia** [comment]
Need to create the directories (cafile, local_cert, local_pk) as said in Upload certificates.
